name: Discord Push Notification

on:
  push:
    branches-ignore: [] # Optional; this includes all branches

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> "$GITHUB_ENV"

      - name: Extract short SHA
        shell: bash
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> "$GITHUB_ENV"

      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        with:
          args: |
            😊 **${{ github.actor }}** pushed to `${{ env.BRANCH_NAME }}`  
            🔗 [View Commit `#${{ env.SHORT_SHA }}`](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}